### PR TITLE
Updated pied 81

### PR DESCRIPTION
**Pull request by aareva-2**
In the homepage the posts are pulled from database. The create post page once submitted adds the posts to the database

### CODE REVIEW

**Review by Schm2000 — COMMENTED** [review]
The create post isn't working for me, it's sending back an error. I'm not sure if this is just me or not, though, I'll send the error over to Abraham.

**Comment by Abner3** [comment]
> The create post isn't working for me, it's sending back an error. I'm not sure if this is just me or not, though, I'll send the error over to Abraham.

Are you sure you're running the backend on your local machine?

**Review by Schm2000 — APPROVED** [review]
Alright I got the code actually working after an extensive amount of help, it looks good to me.

**Review by Abner3 — APPROVED** [review]
Trusting Ender's review. I did not get a chance to test this.

**Pull request merged**
