### PR TITLE
Pied 92

### PR DESCRIPTION
**Pull request by Abner3**
Kody, please add a description of your changes

### CODE REVIEW

**Comment by KodyCoppock** [comment]
This is PR adds a simple footer to our website with links to our other pages, copyright statement, and credit to Clearbit API.

**Comment by Abner3** [comment]
Formatting is a bit off. @KodyCoppock do you think you could fix by this sprint demo? If not, we could accept this pr and you can continue commit to PIED-92 and open another pr
Screen Shot 2021-11-10 at 10 17 44 AM

**Review by EnocFlores — COMMENTED** [review]
Waiting for response on "@testing-library/dom" dependency

**Review by EnocFlores — APPROVED** [review]
approved

**Pull request merged**
