### PR TITLE
Pied-90

### PR DESCRIPTION
**Pull request by caroltang0331**
-added email verification, password reset, sign in, sign up, student profile page.
-files changed: package.json(added proxy), auth folder(3files), pages(11files), app.js(added routes)
-branched from very old branch, plz plz plz merge carefully haha @EnocFlores

### CODE REVIEW

**Review by EnocFlores — COMMENTED** [review]
I will keep looking over this and make sure to integrate our master page into this so we make a clean merge.

**Comment by caroltang0331** [comment]
> I will keep looking over this and make sure to integrate our master page into this so we make a clean merge.

OKAYYY THANKS!!!

**Review by EnocFlores — APPROVED** [review]
Fixed up all the bad changes, should integrate with the UI just fine

**Comment by caroltang0331** [comment]
> Fixed up all the bad changes, should integrate with the UI just fine

Just pulled and tried npm start and it all works! Thank you !!

**Review by Abner3 — APPROVED** [review]
I wasn't able to get it working. @EnocFlores was able to sign up, but not sign in.

**Pull request merged**
