### PR TITLE
Pied 85

### PR DESCRIPTION
**Pull request by EnocFlores**
Updated json

### CODE REVIEW

**Review by Schm2000 — CHANGES_REQUESTED** [review]
The filters bar is definitely broken this time, because all the results vanish after one search and also the Subject bar doesn't show any options. I definitely feel like part of the issue is because we're not getting subject results in the drop-down to begin with, so we should probably forgo holding the results until a search is made and just show some results on the front page regardless, just like what Amin suggested.

**Comment by EnocFlores** [comment]
> The filters bar is definitely broken this time, because all the results vanish after one search and also the Subject bar doesn't show any options. I definitely feel like part of the issue is because we're not getting subject results in the drop-down to begin with, so we should probably forgo holding the results until a search is made and just show some results on the front page regardless, just like what Amin suggested.

The filters have to be updated to reflect the data, because majors was also moved to the requirements. But regardless you want to probably use department instead of majors

**Review by Schm2000 — APPROVED** [review]
Alright then, we can look into fixing the filters.

**Review by Abner3 — APPROVED** [review]
json lgtm

**Pull request merged**
